# This file contains all error codes and Messages
parameters:

    CODE_78: 78
    CODE_78_MSG:  YOU_HAVE_ALREADY_VOTE
    
    CODE_79: 79
    CODE_79_MSG:  YOU_ARE_NOT_OWNER_OF_CLUB
    
    CODE_80: 80
    CODE_80_MSG:  CLUB_CAN_NOT_UNJOIN_YOU_ARE_OWNER
    
    CODE_81: 81
    CODE_81_MSG:  RATING_TYPE_NOT_SUPPPORTED
    
    CODE_86: 86
    CODE_86_MSG:  YOU_ARE_NOT_MEMEBER_OF_CLUB
    
    CODE_87: 87
    CODE_87_MSG:  CLUB_CAN_NOT_UNJOIN_YOU_ARE_OWNER
    
    CODE_88: 88
    CODE_88_MSG:  CLUB_IS_NOT_EXISTS
    
    CODE_95: 95
    CODE_95_MSG:  YOU_MUST_CHOOSE_AN_IMAGE
    
    CODE_98: 98
    CODE_98_MSG:  USER_EXIST_WITH_SAME_EMAIL_ID._YOU_CAN_MAP_YOUR_ACCOUNT
    
    CODE_100: 100
    CODE_100_MSG:  ACCOUNT_IS_NOT_ACTIVE
    
    CODE_101: 101
    CODE_101_MSG:  SUCCESS
    
    CODE_102: 102
    CODE_102_MSG:  USER_PROFILE_IS_NOT_ACTIVE
    
    CODE_111: 111
    CODE_111_MSG:  USER_ID_REQUIRED
    
    CODE_115: 115
    CODE_115_MSG:  GROUP_OWNER_ID_REQUIRED
    
    CODE_116: 116
    CODE_116_MSG:  GROUP_TITLE_IS_REQUIRED
    
    CODE_117: 117
    CODE_117_MSG:  ALREADY_THE_MEMBER_OF_GROUP
    
    CODE_118: 118
    CODE_118_MSG:  REQUEST_IS_PENDING_FOR_OWNER_APPROVAL
    
    CODE_119: 119
    CODE_119_MSG:  NO_NOTIFICATION
    
    CODE_120: 120
    CODE_120_MSG:  NO_GROUP_FOUND
    
    CODE_123: 123
    CODE_123_MSG:  PARENT_STORE_ID_IS_REQUIRED
    
    CODE_126: 126
    CODE_126_MSG:  INVALID_MEMBER_TYPE
    
    CODE_127: 127
    CODE_127_MSG:  NO_IMAGE_FOUND
    
    CODE_128: 128
    CODE_128_MSG:  INVALID_IMAGE
    
    CODE_130: 130
    CODE_130_MSG:  INCOMPLETE_DATA
    
    CODE_131: 131
    CODE_131_MSG:  INVALID_DATE_FORMAT
    
    CODE_132: 132
    CODE_132_MSG:  INVALID_LANGUAGE_CODE
    
    CODE_135: 135
    CODE_135_MSG:  EMAIL_IS_INVALID
    
    CODE_136: 136
    CODE_136_MSG:  ERROR_OCCURED
    
    CODE_137: 137
    CODE_137_MSG:  INVALID_USER
    
    CODE_138: 138
    CODE_138_MSG:  PASSWORD_NOT_MATCHED
    
    CODE_139: 139
    CODE_139_MSG:  PASSWORD_CAN_NOT_BE_BLANK
    
    CODE_140: 140
    CODE_140_MSG:  YOU_MUST_CHOOSE_A_IMAGE_WITH_WIDTH_GREATER_THAN_200_AND_HEIGHT_GREATER_THAN_200
    
    CODE_142: 142
    CODE_142_MSG:  THIS_FACEBOOK_ID_ALREADY_REGISTERD  
    
    CODE_154: 154
    CODE_154_MSG:  CITIZEN_DOES_NOT_EXIT    
    
    CODE_161: 161
    CODE_161_MSG:  BROKER_DOES_NOT_EXIT
    
    CODE_167: 167
    CODE_167_MSG:  NOT_THE_CLUB_REQUEST_SENDER
    
    CODE_174: 174
    CODE_174_MSG:  OLD_PASSWORD_NOT_MATCHED
    
    CODE_176: 176
    CODE_176_MSG:  PRIVACY_TYPE_NOT_SUPPPORTED
    
    CODE_177: 177
    CODE_177_MSG:  PRIVACY_VALUE_NOT_SUPPPORTED
    
    CODE_182: 182
    CODE_182_MSG:  NOTIFICATION_NOT_FOUND
    
    CODE_251: 251
    CODE_251_MSG:  AMOUNT_LESS_THAN_MINIMUM_AMOUNT
    
    CODE_252: 252
    CODE_252_MSG:  CONTRACT_NOT_FOUND
    
    CODE_253: 253
    CODE_253_MSG:  PAYMENT_FAILURE
    
    CODE_302: 302
    CODE_302_MSG:  RECORD_DOES_NOT_EXISTS
    
    CODE_410: 410
    CODE_410_MSG:  INVALID_SHARE_TYPE
    
    CODE_411: 411
    CODE_411_MSG:  CUSTOMER_RATING_REQUIRED
    
    CODE_412: 412
    CODE_412_MSG:  INVALID_RATING
    
    CODE_413: 413
    CODE_413_MSG:  INVALID_STORE
    
    CODE_500: 500
    CODE_500_MSG:  PERMISSION_DENIED
   
    CODE_1001: 1001
    CODE_1001_MSG:  YOU_HAVE_MISSED_A_PARAMETER_
    
    CODE_1002: 1002
    CODE_1002_MSG:  YOU_HAVE_MISSED_A_PARAMETER_LIMIT
    
    CODE_1003: 1003
    CODE_1003_MSG:  ACCOUNT_IS_NOT_ACTIVE 
    
    CODE_1004: 1004
    CODE_1004_MSG:  ALREADY_FOLLOWED 
    
    CODE_1005: 1005
    CODE_1005_MSG:  NO_FOLLOWED 
    
    CODE_1006: 1006
    CODE_1006_MSG:  ALREADY_UNFOLLOWED 
    
    CODE_1012: 1012
    CODE_1012_MSG:  INVALID_COUNTRY_CODE
    
    CODE_1013: 1013
    CODE_1013_MSG:  INVALID_GENDER_TYPE
    
    CODE_1014: 1014
    CODE_1014_MSG:  INVALID_PROFILE_SETTING
    
    CODE_1016: 1016
    CODE_1016_MSG:  BROKER_DOES_NOT_EXIST
    
    CODE_1017: 1017
    CODE_1017_MSG:  INVALID_DATE_FORMAT
    
    CODE_1018: 1018
    CODE_1018_MSG:  EMAIL_IS_INVALID
    
    CODE_1019: 1019
    CODE_1019_MSG:  USER_EXIST
    
    CODE_1020: 1020
    CODE_1020_MSG:  CITIZEN_REGISTERD_ALREADY
    
    CODE_1021: 1021
    CODE_1021_MSG:  USER_DOES_NOT_EXIST
    
    CODE_1022: 1022
    CODE_1022_MSG:  BROKER_REGISTERD_ALREADY
    
    CODE_1023: 1023
    CODE_1023_MSG:  USER_ID_REQUIRED
    
    CODE_1024: 1024
    CODE_1024_MSG:  INVALID_PROFILE_TYPE
    
    CODE_1025: 1025
    CODE_1025_MSG:  VAT_NUMBER_NOT_VALID
    
    CODE_1026: 1026
    CODE_1026_MSG:  IBAN_NOT_VALID
    
    CODE_1027: 1027
    CODE_1027_MSG:  VAT_NUMBER_ALREADY_EXIST
    
    CODE_1028: 1028
    CODE_1028_MSG:  USERNAME_OR_PASSWORD_IS_WRONG
    
    CODE_1029: 1028
    CODE_1029_MSG:  FAILURE
    
    CODE_1030: 1030
    CODE_1030_MSG:  INVALID_USERNAME
    
    CODE_1031: 1031
    CODE_1031_MSG:  THE_PASSWORD_FOR_THIS_USER_HAS_ALREADY_BEEN_REQUESTED_WITHIN_THE_LAST_24_HOURS
    
    CODE_1035: 1035
    CODE_1035_MSG:  ERROR_OCCURED
    
    CODE_1036: 1036
    CODE_1036_MSG:  INVALID_PASSWORD
    
    CODE_1037: 1037
    CODE_1037_MSG:  INVALID_TOKEN
    
    CODE_1039: 1039
    CODE_1039_MSG:  RECORD_DOES_NOT_EXISTS
    
    CODE_1040: 1040
    CODE_1040_MSG:  INVALID_REQUEST
    
    CODE_1041: 1041
    CODE_1041_MSG:  URL_CAN_NOT_BE_EMPTY
    
    CODE_1046: 1046
    CODE_1046_MSG:  EMAIL_ALREADY_VERIFIED
    
    CODE_1047: 1047
    CODE_1047_MSG:  VERIFICATION_LINK_EXPIRED
    
    CODE_1048: 1048
    CODE_1048_MSG:  ACCOUNT_HAS_ALREADY_VERIFIED
    
    CODE_1049: 1049
    CODE_1049_MSG:  TOKEN_NOT_EXIST
    
   
    