<?php

namespace Notification\NotificationBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * EmailNotificationMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailNotificationMongoRepository extends DocumentRepository
{
	
	/**
	 * Search notification messages
	 * @param string $text
	 * @param int $user_id
	 * @param int $offset
	 * @param int $limit
	 * @return object array
	 */
	public function searchBySubjectOrOther($text, $user_id, $offset, $limit)
	{ 
		$qb     = $this->createQueryBuilder();
		$result = $qb->field('receiver_userid')->equals($user_id)
		             ->addOr($qb->expr()->field('subject')->equals(new \MongoRegex('/.*'.$text.'.*/i')))
					 ->addOr($qb->expr()->field('message')->equals(new \MongoRegex('/.*'.$text.'.*/i')))
		             ->limit($limit)
		             ->skip($offset)
				     ->getQuery()
				     ->execute()
		  			 ->toArray(false);
		return $result;
	}
	
	/**
	 * Search notification messages count
	 * @param string $text
	 * @param int $user_id
	 * @return object array
	 */
	public function searchBySubjectOrOtherCount($text, $user_id)
	{
		$qb     = $this->createQueryBuilder('User');
		$result = $qb->field('receiver_userid')->equals($user_id)
					 ->addOr($qb->expr()->field('subject')->equals(new \MongoRegex('/.*'.$text.'.*/i')))
					 ->addOr($qb->expr()->field('message')->equals(new \MongoRegex('/.*'.$text.'.*/i')))
					 ->hydrate(false)
					 ->getQuery()
					 ->execute()
		 			 ->toArray(false);
	    return count($result);

	}
	
}