<?php

namespace Payment\TransactionProcessBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CitizenCreditsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitizenCreditsRepository extends EntityRepository
{
    /**
     * find the pending gift cards for blocked income
     * @param int $user_id
     * @return int amount
     */
    public function calclulateBlockedCredit($user_id) {
        //object of query builder.
        $qb = $this->createQueryBuilder('c');
        try{ 
            $query = $qb->select('sum(c.totalAmount) as amount')
                    ->where('c.citizenId =:userId', 'c.status =:status', 'c.creditType =:creditType')
                    ->setParameter('userId', $user_id)
                    ->setParameter('status', 'PENDING')
                    ->setParameter('creditType', 'GIFT_CARD')
                    ->getQuery();
            $response = $query->getSingleResult();
            if ($response['amount'] != '') {
                return $response['amount'];
            } else {
                return 0;
            } 
        } catch(\Exception $e) {
            return 0;
        }
    }
}
