<?php

namespace Payment\TransactionProcessBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TransactionDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionDetailsRepository extends EntityRepository
{
}
