<?php

namespace Dashboard\DashboardManagerBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * DashboardPostRatingMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DashboardPostRatingMongoRepository extends DocumentRepository
{
}