<?php

namespace Dashboard\DashboardManagerBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * DashboardCommentsMediaMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DashboardCommentsMediaMongoRepository extends DocumentRepository
{
    /**
     * removing the comment media data
     * @param type $comment_id
     * @return boolean
     */
    public function removeDashboardCommentsMedia($comment_id)
    {
            $qb = $this->createQueryBuilder();
            $qb->remove()
                ->field('comment_id')->equals($comment_id)
                ->getQuery()
                ->execute();
            return true;
    }
    
     /**
     * removing the  media data
     * @param type $media_id
     * @return boolean
     */
    public function removeCommentsAllMedia($media_id)
    {
            $qb = $this->createQueryBuilder();
            $qb->remove()
                ->field('id')->equals($media_id)
                ->getQuery()
                ->execute();
            return true;
    }
    
    /**
     * publish media for a comment
     * @param array $media_id
     * @return boolean
     */
    public function publishCommentMediaImage($media_id){
            $this->createQueryBuilder('DashboardCommentsMedia')
                    ->update()
                    ->multiple(true)
                    ->field('is_active')->set(1)
                    ->field('id')->in($media_id)
                    ->getQuery()
                    ->execute();
            
          return true;
    }
    
    /**
     * Finding the comment media
     * @param array $comment_ids
     * @return document object
     */
    public function findCommentMedia($comment_ids) {
            $qb     = $this->createQueryBuilder('u');
            $result = $qb->field('is_active')->equals(1)
                         ->field('comment_id')->in($comment_ids)
                         ->getQuery()
                         ->execute()
                         ->toArray(false);
            return $result;    
    }
}