<?php

namespace Dashboard\DashboardManagerBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PhotoMediaMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoMediaMongoRepository extends DocumentRepository
{
}