PostFeeds\PostFeedsBundle\Document\UserTagFeeds:
    repositoryClass: PostFeeds\PostFeedsBundle\Repository\UserTagFeedsMongoRepository
    type: embeddedDocument
    collection: usertagfeeds
    fields:
        id:
            id:  true
        user_info:
            type: collection	
        created_at:
            type: date
        updated_at:
            type: date
        
           
# php app/console doctrine:mongodb:generate:documents TestFormBundle
# Create Document
# php app/console doctrine:mongodb:generate:repositories TestFormBundle
# Create repositoryd 