parameters:
#    master_data.example.class: Utility\MasterDataBundle\Example
    master_data.masterdata.class: Utility\MasterDataBundle\Services\MasterDataService
services:
#    master_data.example:
#        class: %master_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    master_data.masterdata:
        class: %master_data.masterdata.class%
        arguments: [@doctrine.orm.entity_manager, @doctrine.odm.mongodb.document_manager, @service_container]