<?php

namespace Post\PostBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CommentRatingMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRatingMongoRepository extends DocumentRepository
{

}