<?php

namespace Utility\UniversalNotificationsBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * SharingNotifications
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharingNotifications extends DocumentRepository
{
}