parameters:
#    admin_user_manager_admin_user_manager.example.class: AdminUserManager\AdminUserManagerBundle\Example

services:
#    admin_user_manager_admin_user_manager.example:
#        class: %admin_user_manager_admin_user_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
