<?php

namespace Media\MediaBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ClubAlbumCommentMediaMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubAlbumCommentMediaMongoRepository extends DocumentRepository
{
    /**
     * publish media for a comment
     * @param array $media_id
     * @return boolean
     */
    public function publishClubAlbumCommentMediaImage($media_id){
            $this->createQueryBuilder('ClubAlbumCommentsMedia')
                    ->update()
                    ->multiple(true)
                    ->field('is_active')->set(1)
                    ->field('id')->in($media_id)
                    ->getQuery()
                    ->execute();
            
          return true;
    }
    
    public function getClubAlbumCommentMedia($commentsId) {
        $results = array();
        $qb = $this->createQueryBuilder();
        $results = $qb->field('comment_id')->in($commentsId)
                ->field('is_active')->equals(1)             
                ->getQuery()
                ->execute()
                ->toArray(false);
        return $results;
    }
    
     /**
     * removing the comment media data
     * @param type $comment_id
     * @return boolean
     */
    public function removeClubAlbumCommentsMedia($comment_id)
    {
            $qb = $this->createQueryBuilder();
            $qb->remove()
                ->field('comment_id')->equals($comment_id)
                ->getQuery()
                ->execute();
            return true;
    }
}