<?php

namespace StoreManager\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StorealbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StorealbumRepository extends EntityRepository
{
    /**
     * Get Album  count
     * @param int $store_id
     * @return int
     */
    public function getUserAlbumCount($store_id)
    {
     
         $qb = $this->createQueryBuilder('sm')
                ->select('count(sm.id)')
                ->where('sm.storeId = :sid')
                ->setParameter('sid', $store_id)
                ->getQuery();
             
         $result = $qb->getResult();
         return $result[0][1];
    }
    
     /**
     * Get store album owner id
     *
     * @return integer 
     */
    public function getStoreOwnerId($album_id){
        //initialize the array
        $result=array();
        
        //create the query
        $query=$this->createQueryBuilder('c')
                ->select('us.userId')
                ->innerJoin('StoreManagerStoreBundle:UserToStore','us','WITH','c.storeId=us.storeId')
                ->where('c.id=:aid')
                ->setParameter('aid',$album_id)
                ->getQuery();
        $results = $query->getResult();
        return $results[0]['userId'];
    }
}
