<?php

namespace StoreManager\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TotoCitizenIncomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TotoCitizenIncomeRepository extends EntityRepository
{
    /**
     * Get top citizen as per the income
     * @param int $limit_start
     * @param int $limit_size
     */
    public function getTopCitizenPerIncome($limit_start, $limit_size)
    {
        $result = array();
        $qb = $this->createQueryBuilder('sm')
              ->select()
              ->innerJoin('UserManagerSonataUserBundle:User', 'co', 'WITH', 'co.id = sm.identityId')
              ->where('co.enabled =:isactive')
              ->orderBy('sm.dataUpdate','desc')
              ->orderBy('sm.totalone','desc')
              ->setParameter('isactive','1')
              ->setFirstResult($limit_start)
              ->setMaxResults($limit_size)
              ->getQuery();
             
         $result = $qb->getResult();
         return $result; 
    }
    
    /**
     * Get top citizen as per the income
     * @param int $limit_start
     * @param int $limit_size
     */
    public function getTopCitizenPerIncomeFromDB($limit_start, $limit_size)
    {
        $result = array();
        $qb = $this->_em->createQueryBuilder();             
        $result = $qb->select('sm.id,sm.citizenIncome,sm.userId,sm.totalCitizenIncome')
              ->from('WalletManagementWalletBundle:UserDiscountPosition', 'sm')
              ->innerJoin('UserManagerSonataUserBundle:User', 'co', 'WITH', 'co.id = sm.userId')
              ->where('co.enabled =:isactive')
              ->orderBy('sm.updatedAt','desc')
              ->orderBy('sm.totalCitizenIncome','desc')
              ->setParameter('isactive','1')
              ->setFirstResult($limit_start)
              ->setMaxResults($limit_size)
              ->getQuery()->getResult();
         return $result; 
    }
}
