<?php

namespace Transaction\CitizenIncomeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CiFromProfPersFriendsFollowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiFromProfPersFriendsFollowerRepository extends EntityRepository implements ICitizenIncome 
{
}
