Newsletter\NewsletterBundle\Document\Template:
    repositoryClass: Newsletter\NewsletterBundle\Repository\TemplateMongoRepository
    type: document
    collection: template
    fields:
        id:
            id: true
        title:
            type: string
        body:
            type: string
        author_id:
            type: int
        created_at:
            type: date
