<?php

namespace Message\MessageBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MessageMediaMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageMediaMongoRepository extends DocumentRepository
{
    /**
         * 
         * @param type $thread_id
         * @return type
         */
	public function getAllThreadMedias($thread_id)
	{
            
            $qb     = $this->createQueryBuilder('User');
            $result = $qb
                    ->field('message_id')->in($thread_id)
                    ->getQuery()
                    ->execute()
                    ->toArray(false);
            return $result;
	}
}