<?php

namespace Message\MessageBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ThreadMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadMongoRepository extends DocumentRepository
{
    /**
	 * Search message messages
	 * @param string $text
	 * @param int $user_id
	 * @return object array
	 */
	public function searchBySubjectOrOther($text, $user_id)
	{
		$qb     = $this->createQueryBuilder('User');
		$result = $qb
                             ->field('createdBy_id')->notEqual($user_id)
		             ->addOr($qb->expr()->field('subject')->equals(new \MongoRegex('/.*'.$text.'.*/i')))
                                    ->getQuery()
                                    ->execute()
                                    ->toArray(false);
		return $result;
	}
    /**
	 * Search message 
	 * @param array $thread_id
	 * @param int $user_id
         * @param int $offset
	 * @param int $limit
	 * @return object array
	 */
	public function searchByThreadId($thread_id, $user_id,$offset,$limit)
	{
		$qb     = $this->createQueryBuilder('User');
		$result = $qb
                            ->field('createdBy_id')->notEqual($user_id)
                            ->field('id')->in($thread_id)		            
                                    ->limit($limit)
                                    ->skip($offset)
                                    ->getQuery()
                                    ->execute()
                                    ->toArray(false);
		return $result;
	}

}