<?php

namespace Message\MessageBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ThreadMetadataMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadMetadataMongoRepository extends DocumentRepository
{
        /**
	 * Search notification messages
	 * @param array $threadid
	 * @param int $user_id
	 * @return object array
	 */
	public function searchBySubjectOrOtherThread($threadid, $user_id)
	{

		$qb     = $this->createQueryBuilder('User');
		$result = $qb
                        ->field('thread_id')->in($threadid)
                        ->field('participant_id')->equals($user_id)
				 ->getQuery()
				     ->execute()
					 ->toArray(false);
		return $result;
	}
}