<?php

namespace PostFeeds\PostFeedsBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * SocialProjectAddressMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialProjectAddressMongoRepository extends DocumentRepository
{
}