<?php

namespace StoreManager\PostBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * StoreCommentsMediaMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreCommentsMediaMongoRepository extends DocumentRepository
{
    /**
     * removing the comment media data
     * @param type $comment_id
     * @return boolean
     */
    public function removeCommentsMedia($comment_id)
    {
            $qb = $this->createQueryBuilder();
            $qb->remove()
                ->field('store_comment_id')->equals($comment_id)
                ->getQuery()
                ->execute();
            return true;
    }
    
   
    /**
     * making the media publish.
     * @param type $comment_id
     * @param type $media_array
     * @return true
     */
    public function publishMedia($comment_id, $media_array)
    {
          $this->createQueryBuilder('c')
                    ->update()
                    ->multiple(true)
                    ->field('media_status')->set(1)
                    ->field('id')->in($media_array)
                    ->getQuery()
                    ->execute();
          return true;
    }
    
    public function getCommentMedia($commentsId) {
        $results = array();
        $qb = $this->createQueryBuilder();
        $results = $qb->field('store_comment_id')->in($commentsId)
                ->field('media_status')->equals(1)             
                ->getQuery()
                ->execute()
                ->toArray(false);
        return $results;
    }
}