CardManagement\CardManagementBundle\Entity\WaiverOptions:
    type: entity
    table: null
    repositoryClass: CardManagement\CardManagementBundle\Repository\WaiverOptionsRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        startDate:
            type: date
            column: start_date
        endDate:
            type: date
            column: end_date
        waiverType:
            type: string
            length: 255
            column: waiver_type
        reason:
            type: text
        description:
            type: text
        status:
            type: integer
        createdAt:
            type: datetime
            column: created_at
        itemIds: 
            type: text
        Options:
            type: text
        itemType: 
            type: text
             
    lifecycleCallbacks: {  }
