<?php

namespace Transaction\CommercialPromotionBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Transaction\CommercialPromotionBundle\Interfaces\ICPCustomization;
use Transaction\CommercialPromotionBundle\Document\CouponCP;
use Transaction\CommercialPromotionBundle\Document\TagsCP;

/**
 * CouponCPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponCPRepository extends DocumentRepository implements ICPCustomization {

    public function saveCustomization($coupon, $param) {
        $couponCP = new CouponCP;
        $couponCP->setId($coupon->getId());
        if (isset($param["tag_friends"]) && $param["tag_friends"] > 0) {
            foreach ($param["tag_friends"] as $value) {
                $tag = new TagsCP;
                $tag->setUserId($value["id"]);
                $tag->setName($value["name"]);
                $couponCP->addTagsCp($tag);
            }
        }
        $dm = $this->getDocumentManager();
        $dm->persist($couponCP);
        $dm->flush();
        return $couponCP;
    }

    /**
     * Get extra info for coupon
     * @param int $id_commercial_promotion
     * @return type
     * @throws type
     */
    public function getCustomizationOffer($id_commercial_promotion) {
        $id_commercial_promotion = (int)$id_commercial_promotion;
        $qb = $this->createQueryBuilder('u');
        $result = $qb->field('_id')->equals($id_commercial_promotion)
                ->getQuery()
                ->execute()
                ->toArray(false);
        return $result;
    }

}
