parameters:
    payment_payment_process.transaction_manager.class: Payment\PaymentProcessBundle\Services\TransactionManagerService
    payment_payment_process.interface.class: Payment\PaymentProcessBundle\Factory\ICredit
    payment_payment_process.factory.class: Payment\PaymentProcessBundle\Factory\CreditFactory
    payment_payment_process.entity_coupon.class: Payment\PaymentProcessBundle\Factory\Coupon
    payment_payment_process.entity_giftcard.class: Payment\PaymentProcessBundle\Factory\GiftCard
    payment_payment_process.entity_premimum_position.class: Payment\PaymentProcessBundle\Factory\PremiumPosition
    payment_payment_process.entity_momosy_card.class: Payment\PaymentProcessBundle\Factory\MomosyCard

services:
    #service for transaction manager
    payment_payment_process.transaction_manager:
        class: %payment_payment_process.transaction_manager.class%
        arguments: [@doctrine.orm.entity_manager, @doctrine.odm.mongodb.document_manager, @service_container]

    coupon.credit:
        class: %payment_payment_process.interface.class%
        factory_class: %payment_payment_process.factory.class%
        factory_method: get
        arguments: 
            entity_type: coupon

    premiumposition.credit:
        class: %payment_payment_process.interface.class%
        factory_class: %payment_payment_process.factory.class%
        factory_method: get
        arguments: 
            entity_type: premium_position

    giftcard.credit:
        class: %payment_payment_process.interface.class%
        factory_class: %payment_payment_process.factory.class%
        factory_method: get
        arguments: 
            entity_type: gift_card

    momosycard.credit:
        class: %payment_payment_process.interface.class%
        factory_class: %payment_payment_process.factory.class%
        factory_method: get
        arguments: 
            entity_type: momosy_card
