<?php

namespace SixthContinent\SixthContinentConnectBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ApplicationCoverImgMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationCoverImgMongoRepository extends DocumentRepository {

    /**
     * find the images object
     * @param array $ids
     * @return object array
     */
    public function getApplicationimages($ids) {
        $qb = $this->createQueryBuilder('c');
        $result = $qb->field('id')->in($ids)
                     ->getQuery()
                     ->execute()
                     ->toArray(false);
        return $result;
    }

}
