<?php

namespace SixthContinent\SixthContinentConnectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodesRepository extends EntityRepository
{
    /**
     * get the code for coupon id
     * @param int $coupon_id
     * @return string $code
     */
    public function getCodesByCouponId($coupon_id) {
        $code_prefix= "'00%'";
        $code_table = $this->getEntityManager()->getClassMetadata('SixthContinentConnectBundle:Codes')->getTableName();
        $sql = "SELECT c.code from $code_table as c where coupon_to_active_id=$coupon_id AND code like $code_prefix order by id limit 1";
        try{
            $query = $this->getEntityManager()
                    ->getConnection()
                    ->prepare($sql);
            $query->execute();
            $results = $query->fetchAll();
        } catch(\Exception $e) {
        }
        if (count($results)) {
            return $results[0]['code'];
        }
        return "";
    }
}
