<?php

namespace SixthContinent\SixthContinentConnectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CouponToActiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponToActiveRepository extends EntityRepository
{
    public function getSingleActiveCoupon(){
        $response = null;
        $qb = $this->createQueryBuilder('c');
        $query = $qb
                ->where(
                    'c.is_active= :active'
                )
                ->orderBy('c.orderNumber', 'ASC')
                ->setParameter('active', 1)
                ->setMaxResults(1)
            ->getQuery();
        try{
            $results = $query->getResult();
            if(!empty($results)){
                $response = array_shift($results);
            }
        } catch (\Exception $e) {
            //echo $e->getMessage();
        }
        return $response;
    }
}
