<?php

namespace SixthContinent\SixthContinentConnectBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Utility\ApplaneIntegrationBundle\Model\ApplaneConstentInterface;
use Utility\UtilityBundle\Utils\Utility;

/**
 * SixthcontinentconnectPaymentTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SixthcontinentconnectPaymentTransactionRepository extends EntityRepository {

    CONST PAY_ONCE_CI = 'PAY_ONCE_CI';
    
    /**
     * finding the paypal transaction records
     * @param array $transaction_ids
     */
    public function getAppPaypalTransactions($transaction_ids) {
        $completed_status = ApplaneConstentInterface::COMPLETED;
        $qb = $this->createQueryBuilder('a');
        $query = $qb->select()
                ->where($qb->expr()->in('a.sixthcontinentConnectId', $transaction_ids), $qb->expr()->eq('a.paymentStatus', ':status'))
                ->setParameter('status', $completed_status)
                ->getQuery();
        $result = $query->getResult();
        return $result;
    }
    
    /**
     * getting the transaaction of payonce ci type of preious day.
     */
    public function getCiTransactions() {
        $yesterday  = new \DateTime('yesterday');
        $start_date = $yesterday->format('Y-m-d');
        $today      = new \DateTime('today');
        $end_date   = $today->format('Y-m-d');
        $reason = self::PAY_ONCE_CI;
        $completed_status = ApplaneConstentInterface::COMPLETED;
        //object of query builder.
        $qb = $this->createQueryBuilder('c');
        $query = $qb->select()
                ->where('c.date >=:start_at', 'c.date <:end_at', 'c.reason =:reason', 'c.paymentStatus =:status')
                ->setParameter('start_at', $start_date)
                ->setParameter('end_at', $end_date)
                ->setParameter('reason', $reason)
                ->setParameter('status', $completed_status)
                ->getQuery();
        $response = $query->getResult();
        return $response;
    }
}
