<?php

namespace SixthContinent\SixthContinentConnectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TamoilExportCounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TamoilExportCounterRepository extends EntityRepository {

  /**
   * get the tamoil export counter.
   */
  public function getExportCounter() {
    $results = array();
    try {
      $qb = $this->createQueryBuilder('o');
      $query = $qb->select('o.id', 'o.counter')
              ->setFirstResult(0)
              ->setMaxResults(1)
              ->getQuery();
      $results = $query->getResult();
    } catch (\Exception $e) {
      
    }
    if (count($results)) {
      return $results[0];
    }
    return $results;
  }

}
