Affiliation\AffiliationManagerBundle\Entity\AffiliationBroker:
    type: entity
    table: null
    repositoryClass: Affiliation\AffiliationManagerBundle\Entity\AffiliationBrokerRepository
    indexes:
        index_fromid_toid_AffiliationBroker:
            columns: [from_id,to_id]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fromId:
            type: integer
            column: from_id
        toId:
            type: integer
            column: to_id
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks: {  }
