<?php

namespace Utility\ApplaneIntegrationBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * SubscriptionPaymentNotificationLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionPaymentNotificationLogRepository extends DocumentRepository
{
    /**
     * Check if notification sent
     * @param int $user_id
     * @param int $shop_id
     * @param string $type
     * @return array $result
     */
    public function checkSubscriptionTransactionPaymentLogs($user_id, $shop_id, $type)
    {
        $result = array();
        $user_id = (int)$user_id;
        $shop_id = (int)$shop_id;
        $type    = (string)$type;
        //create the query
        $qb     = $this->createQueryBuilder();
        $result = $qb->field('to_shop_id')->equals($shop_id)
                  ->field('to_user_id')->equals($user_id)
                  ->field('is_active')->equals(1)
                  ->field('notification_type')->equals($type)
                  ->field('send_count')->lt(9)
                  ->getQuery()
                  ->execute()
		  ->toArray(false);
        if($result){
           return $result['0'];
        }
        return $result;
    }
    
    /**
     * find failed subscription transaction logs
     * @return array
     */
    public function findSubscriptionPaymentLogs()
    {
        $result = array();
        //create the query
        $qb     = $this->createQueryBuilder();
        $result = $qb
                  ->field('is_active')->equals(1)
                  ->field('notification_type')->equals('SUBSCRIPTION_PENDING_PAYMENT')
                  ->field('send_count')->lt(9)
                  ->getQuery()
                  ->execute()
		  ->toArray(false);
        if($result){
           return $result;
        }
        return $result;
    }
}