<?php

namespace Utility\ApplaneIntegrationBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TransactionNotificationLog
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionNotificationLogRepository extends DocumentRepository
{
    /**
     * Check if notification sent
     */
    public function checkNotificationSent($shop_id)
    {
        $result = array();
        //create the query
        $qb     = $this->createQueryBuilder();
        $result = $qb->field('to_shop_id')->equals($shop_id)
                  ->field('is_active')->equals(true)
                  ->field('send_count')->lt(8)
                  ->getQuery()
                  ->execute()
		  ->toArray(false);
        if($result){
           return $result['0'];
        }
        return $result;
    }
    
     /**
     * find failed transaction logs
     * @return type
     */
    public function findRegistrationLogs()
    {
        $result = array();
        //create the query
        $qb     = $this->createQueryBuilder();
        $result = $qb
                  ->field('is_active')->equals(true)
                  ->field('notification_type')->equals('REG_FEE_NOT_PAID')
                  ->field('send_count')->lt(9)
                  ->getQuery()
                  ->execute()
		  ->toArray(false);
        if($result){
           return $result;
        }
        return $result;
    }
}