<?php

namespace UserManager\Sonata\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
//use AppBundle\Entity\EducationDetails;

/**
 * EducationDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailVerificationTokenRepository extends EntityRepository
{

    
}

