<?php

namespace UserManager\Sonata\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserDeletedAssignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDeletedAssignRepository extends EntityRepository
{
    public function getDeleteUserData($limit, $offset){
        $qb = $this->createQueryBuilder('c');
        $query = $qb
              ->where('c.assignId =:type')		
	      ->setParameter('type', 0)
              ->setMaxResults($limit)
              ->setFirstResult($offset)
              ->getQuery();
        $response = $query->getResult();
        return $response;
    }
}
