parameters:
#    photo_comment.example.class: Utility\PhotoCommentBundle\Example

services:
#    photo_comment.example:
#        class: %photo_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
