<?php

namespace Transaction\TransactionBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CardSoldoErrorLogMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardSoldoErrorLogMongoRepository extends DocumentRepository
{
}