<?php

namespace Transaction\TransactionBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TransictionImportLogsMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransictionImportLogsMongoRepository extends DocumentRepository
{
}