<?php

namespace ExportManagement\ExportManagementBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * GiftcardExportLogsMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiftcardExportLogsMongoRepository extends DocumentRepository
{
}