<?php

namespace ExportManagement\ExportManagementBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ProfileExportMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileExportMongoRepository extends DocumentRepository
{
}