<?php
namespace UserManager\Sonata\UserBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessToken extends EntityRepository
{
	/**
	 * Get token
	 * @param string $token
	 * @return object array
	 */
	public function findOneByToken($token)
	{
		return $token;
	}
}