<?php

namespace UserManager\Sonata\UserBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * StudyListMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudyListMongoRepository extends DocumentRepository
{

    /**
    * Get Suggestion Search
    * @param \Symfony\Component\HttpFoundation\Request $request
    * @return string
    */
    public function getSuggestionSearch($text, $type){
        $results = array();
        //get all groups assigned to user
        $qb = $this->createQueryBuilder();
        $results = $qb->field('type')->equals($type)
                ->field('name')->equals(new \MongoRegex('/.*' . $text . '.*/i'))
                ->sort('id', 'desc')
                ->getQuery()
                ->execute()
                ->toArray(false);
        
        return $results;
    }

}
