<?php

namespace UserManager\Sonata\UserBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserPhotoMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPhotoMongoRepository extends DocumentRepository
{
}