<?php
namespace ExportManagement\ExportManagementBundle\Model;
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
interface ExportConstantInterface {

    const REGISTRATION_CAUSALE = 'FTAFF';
    const SIX_PERCENT_CAUSALE = 'RC6PC';
    const TEN_PERCENT_CAUSALE = 'FT10P';
    const SUBSCRIPTION_PERCENT_CAUSALE = 'FTCOM';
    const REGISTRATION_CODICE = 'AFF';
    const SIX_PERCENT_CODICE = '6PC';
    const TEN_PERCENT_CODICE = '10PC';
    const SUBSCRIPTION_PERCENT_CODICE = 'COME';
    const REGISTRATION_DESCRIPTION1 = 'CORRISPETTIVO PER AFFILIAZIONE ED';
    const SIX_PERCENT_DESCRIPTION1 = "CORRISPETTIVO PUBBLICITA'";
    const TEN_PERCENT_DESCRIPTION1 = "CORRISPETTIVO PUBBLICITA'";
    const SUBSCRIPTION_PERCENT_DESCRIPTION1 = 'CORRISPETTIVO MENSILE ACQUISTO';
    const REGISTRATION_DESCRIPTION2 = 'ADESIONE AL CIRCUITO PROMOZIONALE SIXTHCONTINENT ITALIA SRL';
    const SIX_PERCENT_DESCRIPTION2 = "PER VENDITE EFFETTUATE:CODICE PRELIEVO:(%s)\nTRANSAZIONI DI RIFERIMENTO:\n";
    const TEN_PERCENT_DESCRIPTION2 = "PER VENDITE EFFETTUATE\nTRANSAZIONI DI RIFERIMENTO:\n";
    const SUBSCRIPTION_PERCENT_DESCRIPTION2 = 'IN ABBONAMENTO AL CIRCUITO SIXTHCONTINENT PER VENDITA SHOPPING CARD';
    const CAUSALE = 'CAUSALE';
    const CODICE  = 'CODICE';
    const DESCRIZIONE = 'DESCRIZIONE';
    const DESCRIZIONE2 = 'DESCRIZIONE2';
    const R = 'R';
    const S = 'S';
    const T = 'T';
    const C = 'C';
    const SALES_DESCRIPTION2_COLUMN = 'G';
    const SALES_CODICE_COLUMN = 'E';
}
