Transaction\CommercialPromotionBundle\Document\VoucherCP:
    repositoryClass: Transaction\CommercialPromotionBundle\Repository\VoucherCPRepository 
    type: document
    collection: vouchercp
    fields:
        id:
            id: true
            strategy: NONE
        images_cp:
           embedded: true
           type: many
           targetDocument: Transaction\CommercialPromotionBundle\Document\ImagesCP
           cascade: all
        description:
            type: string
        url_confirmation:
            type: string
        html_page:
            type: string
#        key_words_cp:
#           embedded: true
#           type: many
#           targetDocument: Transaction\CommercialPromotionBundle\Document\KeyWordsCP
#           cascade: all	
           
# php app/console doctrine:mongodb:generate:documents PostPostBundle
# Create Document
# php app/console doctrine:mongodb:generate:repositories TestFormBundle
# Create repositoryd 