parameters:
#    post_post.example.class: Post\PostBundle\Example

services:
#    post_post.example:
#        class: %post_post.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
