<?php

namespace Payment\PaymentDistributionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NonDistributedCIAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NonDistributedCIAmountRepository extends EntityRepository
{
    /**
     * function for deleting the non distributed amount
     * @param type $transaction_id
     * @return type
     */
    public function deleteNonDistributedAmount($transaction_id) {
        $isDeleted = $this->createQueryBuilder("u")
            ->delete()
            ->where('u.transactionId  = :transaction_id')->setParameter("transaction_id", $transaction_id)            
            ->getQuery()->execute();

        return $isDeleted;
    }
}
