parameters:
#    utility_barcode.example.class: Utility\BarcodeBundle\Example

services:
#    utility_barcode.example:
#        class: %utility_barcode.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
