<?php

namespace Newsletter\NewsletterBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TemplateMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateMongoRepository extends DocumentRepository
{
}