<?php

namespace Utility\MasterDataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageCodeRepository extends EntityRepository
{
     /**
    * Privacy Setting List
    * @return object array
    */
    public function getLanguageList($langCode){ 
        try{
        //object of query builder.
        $qb = $this->createQueryBuilder('c');
        $query = $qb->select('c.id, code.languageString as language_string')
                ->innerJoin('MasterDataBundle:LanguageCodeByLang', 'code', 'WITH', 'code.languageNameCode = c.languageName')
                ->where('code.langCode =:langCode','c.status =:status')
                ->setParameter('langCode',$langCode )
                ->setParameter('status',1)
                ->getQuery();
        $response = $query->getResult();
        return $response;
        }catch(\Exception $e){
            return array();
        }
    }
}
