<?php

namespace Utility\MasterDataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrivacySettingCodeByLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivacySettingCodeByLangRepository extends EntityRepository
{
}
