<?php

namespace Utility\MasterDataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VisibilityCodeByLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisibilityCodeByLangRepository extends EntityRepository
{
}
