<?php

namespace Acme\GiftBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MovimenLogsMongoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimenLogsMongoRepository extends DocumentRepository
{
}