Payment\PaymentDistributionBundle\Entity\CitizenIncomeGain:
    type: entity
    table: citizenincomegain
    repositoryClass: Payment\PaymentDistributionBundle\Repository\CitizenIncomeGainRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        userId:
            type: integer
            column: user_id
        purchaserId:
            type: bigint
            column: purchaser_id
        income:
            type: bigint
        shopId:
           type: integer
           column: shop_id        
        transactionId:
            type: string
            length: 255
            column: transaction_id
        date:
            type: datetime
        status:
            type: integer
            column: status
            options:
                default: 0
        type:
            type: string
            length: 255
            column: type
    lifecycleCallbacks: {  }
