## YAML Template.
---
Votes\VotesBundle\Document\Votes:
    repositoryClass: Votes\VotesBundle\Repository\VotesMongoRepository
    type: document
    collection: votes
    fields:
        id:
            id:  true
        item_type:
            type: string
        item_id:
            type: string
        voter_id:
            type: string
        voter_profile_id:
            type: string
        voter_type:
            type: string
        vote:
            type: int
        created_at:
            type: date
        updated_at:
            type: date