parameters:
#    store_manager_post.example.class: StoreManager\PostBundle\Example

services:
#    store_manager_post.example:
#        class: %store_manager_post.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
